version: '3.7'

services:
  bot:
    build:
      context: bot/
    # ports:
    #   - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - YANDEX_CLOUD_TOKEN=${YANDEX_CLOUD_TOKEN}
      - YANDEX_CLOUD_FOLDER=${YANDEX_CLOUD_FOLDER}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    networks:
      - ywb_network

  db:
    image: postgres:16.1
    restart: always
    environment:
      - POSTGRES_USER=${DB_ROOT_USER}
      - POSTGRES_PASSWORD=${DB_ROOT_USER_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    networks:
      - ywb_network
      
volumes:
  db-data: {}

networks:
  ywb_network:
    name: ywb_network
    driver: bridge